from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from ..database.database import get_db
from ..services.prophet_service import get_prophet_prediction
from datetime import datetime
from ..database import models

router = APIRouter()

@router.get("/predict")
def predict_stock(
    station_id: str, 
    fuel_type: str, 
    periods: int = Query(24, description="Number of 5-min intervals to predict"),
    db: Session = Depends(get_db)
):
    """Returns forecasted stock levels with LLM narrative annotation."""
    result = get_prophet_prediction(db, station_id, fuel_type, periods)
    return result




@router.get("/report")
def generate_report(
    station_id: str = Query(..., description="ID of the station"),
    fuel_type: str = Query(..., description="Type of fuel (e.g., Gasoil50)"),
    db: Session = Depends(get_db)
):
    """
    Generates a comprehensive Markdown report including current stock, 
    recent alerts, and Prophet/LLM forecast.
    """
    # 1. Récupérer le stock actuel (le dernier enregistrement)
    latest_fuel = db.query(models.FuelData).filter(
        models.FuelData.station_id == station_id,
        models.FuelData.fuel_type == fuel_type
    ).order_by(models.FuelData.timestamp.desc()).first()

    if not latest_fuel:
        return {"report_markdown": f"# Report Error\nNo data found for station {station_id} and fuel {fuel_type}."}

    stock = latest_fuel.stock_liters
    cap = latest_fuel.capacity_liters
    stock_pct = (stock / cap * 100) if cap and cap > 0 else 0

    # 2. Récupérer les alertes récentes (les 5 dernières pour ne pas surcharger le rapport)
    recent_alerts = db.query(models.Alert).filter(
        models.Alert.station_id == station_id,
        models.Alert.fuel_type == fuel_type
    ).order_by(models.Alert.timestamp.desc()).limit(5).all()

    # 3. Récupérer la prévision Prophet et la narration (que tu as codée tout à l'heure)
    prediction = get_prophet_prediction(db, station_id, fuel_type, periods=12)
    narrative = prediction.get("narrative", "Forecast narrative currently unavailable.")

    # 4. GÉNÉRATION DU FALLBACK MARKDOWN (En attendant le vrai LLM)
    date_str = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    md_lines = [
        f"# 📊 Automated Inventory Report",
        f"**Station:** {station_id} | **Fuel:** {fuel_type} | **Date:** {date_str}",
        "\n---",
        
        "\n## 1. Current Inventory Status",
        f"- **Current Stock:** {stock:.0f}L ({stock_pct:.1f}% of maximum capacity)",
        f"- **Recent Consumption:** {latest_fuel.sales_last_5min_liters:.0f} L/5min",
        f"- **Current Price:** {latest_fuel.price_tnd:.3f} TND",
        
        "\n## 2. Recent Alerts (Last 24h)"
    ]

    if recent_alerts:
        for a in recent_alerts:
            icon = "🔴" if a.severity.lower() == "critical" else "🟡"
            md_lines.append(f"- {icon} **{a.alert_type}** : {a.message}")
    else:
        md_lines.append("- ✅ *No recent alerts detected for this fuel type.*")

    md_lines.extend([
        "\n## 3. AI Forecast & Recommendations",
        f"> {narrative}",
        
        "\n---",
        "\n*Report automatically generated by the AI Reporting Agent.*"
    ])

    report_markdown = "\n".join(md_lines)

    # 5. On retourne le format JSON convenu
    return {
        "report_markdown": report_markdown
    }